### ISSUE TITLE
US 01.06.01 -Owner/Experimenter Trial results histogram

### ISSUE THREAD

**Issue by archit-soni** [CMPUT301W21T30/RocketApp#8]
As an owner or experimenter, I want to see histograms of the results of trials.

(Risk : Medium)
(Hours : 3)

**Comment by mikegreber** [comment]
@archit-soni @qasemsai I added a timestamp to the trials in my latest pull request, should be useful for plotting the results over time

**Comment by archit-soni** [comment]
Histogram added, if anybody wants to test checkout stats-graphs branch

**Comment by mikegreber** [comment]
Looks good if you wanna make a pull request

**Comment by archit-soni** [comment]
Will do a combined pull for histogram and time plots in the same activity view, either tomorrow or after midterm
